### ISSUE TITLE
 Hassio 3023.09.3 ERROR:asyncio:Task exception was never retrieved

### ISSUE THREAD

**Issue by Buktahula** [gluap/pyess#23]
Since I have updated my HA OS to 3023.09.3 and the addon to 0.0.6 simultaneously any sensors are available anymore.

The log says the following. What’s the problem?

-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
s6-rc: info: service legacy-services successfully started
[11:33:53] INFO: Initialize the essmqtt configuration...
INFO:pyess.aio_ess:fetching auth key
INFO:pyess.essmqtt:starting send loop
ERROR:asyncio:Task exception was never retrieved
future: <Task finished name='Task-17' coro=<_main..handle_control() done, defined at /usr/local/lib/python3.8/site-packages/pyess/essmqtt.py:180> exception=MqttError('Disconnected during message iteration')>
Traceback (most recent call last):
File "/usr/local/lib/python3.8/site-packages/pyess/essmqtt.py", line 182, in handle_control
async for msg in messages:
File "/usr/local/lib/python3.8/site-packages/aiomqtt/client.py", line 857, in _generator
raise MqttError(msg)
aiomqtt.error.MqttError: Disconnected during message iteration
ERROR:asyncio:Task exception was never retrieved
future: <Task finished name='Task-18' coro=<_main..handle_control() done, defined at /usr/local/lib/python3.8/site-packages/pyess/essmqtt.py:180> exception=MqttError('Disconnected during message iteration')>
Traceback (most recent call last):
File "/usr/local/lib/python3.8/site-packages/pyess/essmqtt.py", line 182, in handle_control
async for msg in messages:
File "/usr/local/lib/python3.8/site-packages/aiomqtt/client.py", line 857, in _generator
raise MqttError(msg)
aiomqtt.error.MqttError: Disconnected during message iteration
ERROR:asyncio:Task exception was never retrieved
future: <Task finished name='Task-19' coro=<_main..handle_control() done, defined at /usr/local/lib/python3.8/site-packages/pyess/essmqtt.py:180> exception=MqttError('Disconnected during message iteration')>
Traceback (most recent call last):
File "/usr/local/lib/python3.8/site-packages/pyess/essmqtt.py", line 182, in handle_control
async for msg in messages:
File "/usr/local/lib/python3.8/site-packages/aiomqtt/client.py", line 857, in _generator
raise MqttError(msg)
aiomqtt.error.MqttError: Disconnected during message iteration
ERROR:asyncio:Task exception was never retrieved
future: <Task finished name='Task-23' coro=<_main..handle_control() done, defined at /usr/local/lib/python3.8/site-packages/pyess/essmqtt.py:180> exception=MqttError('Disconnected during message iteration')>
Traceback (most recent call last):
File "/usr/local/lib/python3.8/site-packages/pyess/essmqtt.py", line 182, in handle_control
async for msg in messages:
File "/usr/local/lib/python3.8/site-packages/aiomqtt/client.py", line 857, in _generator
raise MqttError(msg)
aiomqtt.error.MqttError: Disconnected during message iteration
ERROR:asyncio:Task exception was never retrieved
future: <Task finished name='Task-24' coro=<_main..handle_control() done, defined at /usr/local/lib/python3.8/site-packages/pyess/essmqtt.py:180> exception=MqttError('Disconnected during message iteration')>
Traceback (most recent call last):
File "/usr/local/lib/python3.8/site-packages/pyess/essmqtt.py", line 182, in handle_control
async for msg in messages:
File "/usr/local/lib/python3.8/site-packages/aiomqtt/client.py", line 857, in _generator
raise MqttError(msg)
aiomqtt.error.MqttError: Disconnected during message iteration
ERROR:asyncio:Task exception was never retrieved
future: <Task finished name='Task-25' coro=<_main..handle_control() done, defined at /usr/local/lib/python3.8/site-packages/pyess/essmqtt.py:180> exception=MqttError('Disconnected during message iteration')>
Traceback (most recent call last):
File "/usr/local/lib/python3.8/site-packages/pyess/essmqtt.py", line 182, in handle_control
async for msg in messages:
File "/usr/local/lib/python3.8/site-packages/aiomqtt/client.py", line 857, in _generator
raise MqttError(msg)
aiomqtt.error.MqttError: Disconnected during message iteration
WARNING:pyess.essmqtt:Expected exception while talking go ESS or MQTT server, restarting in 60 seconds.Usually this means the server is slow to respond or unreachable.
INFO:pyess.aio_ess:fetching auth key
INFO:pyess.essmqtt:starting send loop

**Comment by gluap** [comment]
No activity for a month - feel free to reopen.
